apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinstest
  labels:
    app: jenkinstest
    name: jenkinstest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkinstest
  template:
    metadata:
      labels:
        app: jenkinstest
    spec:
      containers:
        - name: jenkinstest
          image: pm3ndoza/jeninstest:43
          ports:
            - containerPort: 8080

#----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: jenkinstest-svc
spec:
  selector:
    app: jenkinstest
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
